### ISSUE TITLE
Soft clear does not preserve scroll buffer on gnome-terminal

### ISSUE THREAD

**Issue by maxmilton** [lukeed/console-clear#4]
The control sequence `\x1Bc` does not keep the scroll back buffer when used in gnome-terminal on Linux.

I'm not sure about other terminal emulators on Linux but this definitely effects gnome-terminal. It could also be an issue on other modern terminal emulators on Linux and BSD. My system info for reference:

Gnome terminal version `3.30`

```sh
$ env | grep TERM
TERM=xterm-256color
```

```sh
$ uname -a
Linux maxarch 4.18.9-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 19 21:19:17 UTC 2018 x86_64 GNU/Linux
```

```sh
$ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

**Comment by maxmilton** [comment]
I've found that using `\x1B[H\x1B[2J` will produce the desired result. Not sure about compatibility with common terminals on BSD, macOS, or Windows though.

**Comment by lukeed** [comment]
Cool, thanks!

I just got a windows machine this weekend so I'll test out compatibility

**Comment by lukeed** [comment]
Tested; works everywhere. Thanks!
